"""Core contracts, validation, routing, and result normalization."""

from saida.core.analytics_registry import (
    AnalyticsConceptSpec,
    AnalyticsFamilySpec,
    AnalyticsMethodSpec,
    AnalyticsRelationSpec,
    AnalyticsRegistry,
    build_default_analytics_registry,
    get_analytics_registry,
)
from saida.core.artifact_store import ArtifactStore
from saida.core.artifacts import (
    FrameArtifact,
    RuntimeArtifact,
    ScalarArtifact,
    SeriesArtifact,
    VerificationArtifact,
    artifact_from_value,
)
from saida.core.contracts import (
    AnalysisInterpretation,
    AnalysisPlan,
    AnalysisResult,
    ColumnProfile,
    Dataset,
    DatasetProfile,
    ExecutionTraceEvent,
    ExecutionArtifact,
    ForecastAnalysisResult,
    ForecastResult,
    Metric,
    MLReadinessProfile,
    ModelSpec,
    ModelTrainingResult,
    NodeExecutionResult,
    PlanStep,
    PlanInput,
    PredictionResult,
    SourceContext,
    StepInputRef,
    StepOutputSpec,
    TableArtifact,
    TrainResult,
)
from saida.core.dag_contract import ArtifactTypeSpec, DagExecutionContract, build_default_dag_execution_contract
from saida.core.result_canonicalization import ResultBuilder, ResultCanonicalizer
from saida.core.routing import BackendRouter
from saida.core.validation import PlanValidator

__all__ = [
    "AnalysisPlan",
    "AnalysisInterpretation",
    "AnalysisResult",
    "AnalyticsConceptSpec",
    "AnalyticsFamilySpec",
    "AnalyticsMethodSpec",
    "AnalyticsRelationSpec",
    "AnalyticsRegistry",
    "ArtifactStore",
    "ArtifactTypeSpec",
    "BackendRouter",
    "artifact_from_value",
    "build_default_analytics_registry",
    "build_default_dag_execution_contract",
    "ColumnProfile",
    "DagExecutionContract",
    "Dataset",
    "DatasetProfile",
    "ExecutionTraceEvent",
    "ExecutionArtifact",
    "FrameArtifact",
    "ForecastAnalysisResult",
    "ForecastResult",
    "get_analytics_registry",
    "Metric",
    "MLReadinessProfile",
    "ModelSpec",
    "ModelTrainingResult",
    "NodeExecutionResult",
    "PlanInput",
    "PlanStep",
    "PlanValidator",
    "PredictionResult",
    "ResultBuilder",
    "ResultCanonicalizer",
    "RuntimeArtifact",
    "ScalarArtifact",
    "SeriesArtifact",
    "SourceContext",
    "StepInputRef",
    "StepOutputSpec",
    "TableArtifact",
    "TrainResult",
    "VerificationArtifact",
]
