"""Core contracts, validation, routing, and result normalization."""

from saida.core.analytics_registry import (
    AnalyticsFamilySpec,
    AnalyticsMethodSpec,
    AnalyticsRegistry,
    build_default_analytics_registry,
    get_analytics_registry,
)
from saida.core.capability_registry import (
    CapabilityEdge,
    CapabilityNode,
    CapabilityRegistry,
    build_default_capability_registry,
    get_capability_registry,
)
from saida.core.context import SourceContextParser
from saida.core.contracts import (
    AnalysisInterpretation,
    AnalysisPlan,
    AnalysisRequest,
    AnalysisResult,
    ColumnProfile,
    Dataset,
    DatasetProfile,
    ExecutionTraceEvent,
    ForecastAnalysisResult,
    ForecastResult,
    Metric,
    MLReadinessProfile,
    ModelSpec,
    ModelTrainingResult,
    PlanStep,
    PlanInput,
    PredictionResult,
    RequestLike,
    SourceContext,
    TableArtifact,
    TrainResult,
)
from saida.core.discovery import DatasetProfiler, SchemaDiscoveryService
from saida.core.result_canonicalization import ResultBuilder, ResultCanonicalizer
from saida.core.routing import BackendRouter
from saida.core.validation import PlanValidator

__all__ = [
    "AnalysisPlan",
    "AnalysisInterpretation",
    "AnalysisRequest",
    "AnalysisResult",
    "AnalyticsFamilySpec",
    "AnalyticsMethodSpec",
    "AnalyticsRegistry",
    "BackendRouter",
    "build_default_analytics_registry",
    "build_default_capability_registry",
    "CapabilityEdge",
    "CapabilityNode",
    "CapabilityRegistry",
    "ColumnProfile",
    "Dataset",
    "DatasetProfiler",
    "DatasetProfile",
    "ExecutionTraceEvent",
    "ForecastAnalysisResult",
    "ForecastResult",
    "get_analytics_registry",
    "get_capability_registry",
    "Metric",
    "MLReadinessProfile",
    "ModelSpec",
    "ModelTrainingResult",
    "PlanInput",
    "PlanStep",
    "PlanValidator",
    "PredictionResult",
    "RequestLike",
    "ResultBuilder",
    "ResultCanonicalizer",
    "SchemaDiscoveryService",
    "SourceContext",
    "SourceContextParser",
    "TableArtifact",
    "TrainResult",
]
